
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sachin
    url: jdbc:mysql://localhost:3306/nit1
    password: password
    

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    
